version: "3.8"

networks:
  local:
    driver: bridge

services:
  blueprint:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blueprint
    image: blueprint:1.0
    environment:
      - BLUEPRINT_ENVIRONMENT=docker
      - BLUEPRINT_RELEASE_VERSION=1.0
      - BLUEPRINT_VERSION=unavailable
    expose:
      - 3000
    networks:
      - local
